export interface FerramentaPassbolt {
  nome: string;
  categoria: string;
  tipo: string;
  url: string;
  descricao: string;
}

export const ferramentas: FerramentaPassbolt[] = [
  { nome: "AirByte - API", categoria: "Dados e Analytics", tipo: "Passbolt", url: "airbyte-c2dc4574f078cdf5.suno.com.br/api/v1", descricao: "" },
  { nome: "airbyte-dev", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://airbyte-dev-23izk7ttvgkxud3v.suno.com.br/", descricao: "" },
  { nome: "airbyte-v2", categoria: "Dados e Analytics", tipo: "Passbolt", url: "airbyte-c2dc4574f078cdf5.suno.com.br", descricao: "" },
  { nome: "AirFlow - API", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://airflow-v2-3438dd66106286d7.suno.com.br/api/v1", descricao: "" },
  { nome: "airflow-dev", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://airflow-dev-7fe4e8435328fd9e.suno.com.br/", descricao: "" },
  { nome: "Cielo", categoria: "Financeiro", tipo: "Passbolt", url: "https://minhaconta2.cielo.com.br/", descricao: "" },
  { nome: "Dremio (Airflow)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://dremio-2mvj4w04rnzorb2xnk71r945ja6h5nbd.suno.com.br", descricao: "" },
  { nome: "E-mail statusinvestbr@gmail.com youtube", categoria: "Conteúdo", tipo: "Passbolt", url: "gmail.com", descricao: "" },
  { nome: "E-mail sunoresearch@gmail.com Youtube", categoria: "Conteúdo", tipo: "Passbolt", url: "gmail.com", descricao: "" },
  { nome: "E-mail Time Dados", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Google - Eleven", categoria: "Outros", tipo: "Passbolt", url: "https://accounts.google.com", descricao: "" },
  { nome: "Instagram Baroni", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Eleven", categoria: "Marketing", tipo: "Passbolt", url: "www.Instagram.com", descricao: "" },
  { nome: "Instagram FIIs.com.br", categoria: "Marketing", tipo: "Passbolt", url: "instagram.com", descricao: "" },
  { nome: "Instagram Marcos Correa", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Status Invest", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Suno Asset", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Suno Noticias", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram sunoresearch", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Tiago Reis", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Vitor Duarte", categoria: "Marketing", tipo: "Passbolt", url: "instagam.com", descricao: "" },
  { nome: "Instagram Waka (Felipe)", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Linktree Tiago Instagram", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Multichannel - Admin", categoria: "Marketing", tipo: "Passbolt", url: "https://11pro-dev.com.br", descricao: "" },
  { nome: "Multichannel -Conteúdos", categoria: "Marketing", tipo: "Passbolt", url: "https://eleven.11pro-dev.com.br", descricao: "" },
  { nome: "Office 365 Power BI - Contato (Admin)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://powerbi.microsoft.com/pt-br/landing/signin/", descricao: "" },
  { nome: "OVH powerbi-v2", categoria: "Infraestrutura", tipo: "Passbolt", url: "15.204.212.182", descricao: "" },
  { nome: "Power BI - Time Dados - powerbi-service-airflow", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://app.powerbi.com/home?language=pt-BR", descricao: "" },
  { nome: "Snowflake - INTEGRATION USER", categoria: "Dados e Analytics", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "TIKTOK Suno Noticias", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "TIKTOK Suno Research", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "TikTok Tiago Reis", categoria: "Marketing", tipo: "Passbolt", url: "https://www.tiktok.com/pt-BR/", descricao: "" },
  { nome: "TikTok Vitor Duarte", categoria: "Marketing", tipo: "Passbolt", url: "https://www.tiktok.com/pt-BR/", descricao: "" },
  { nome: "TVs Suno Sede", categoria: "Outros", tipo: "Passbolt", url: "https://docs.google.com/spreadsheets/d/1ebs5q3iWR8SgcXq_fK9VRCNpEDiPQIduRpvo6kREu2U/edit#gid=1176315036", descricao: "" },
  { nome: "Twitter Baroni", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Twitter fiis", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/FIIsbr", descricao: "" },
  { nome: "Twitter Status Invest", categoria: "Marketing", tipo: "Passbolt", url: "twitter.com", descricao: "" },
  { nome: "Twitter Suno", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Twitter Suno Asset", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Twitter Suno Noticias", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Twitter Tiago", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Youtube Suno Asset", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "API - Status Invest", categoria: "Produto", tipo: "Passbolt", url: "https://marketdata.statusinvest.com.br/swagger/index.html", descricao: "" },
  { nome: "BTG API", categoria: "Financeiro", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Bume.io Instagram", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Dremio", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://dremio-d41d8cd98f00b204e9800998ecf8427e.suno.com.br/source/Suno%20Data%20Hub/folder/suno-datahub", descricao: "" },
  { nome: "Dremio (Metabase)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "34.197.117.238", descricao: "" },
  { nome: "Dremio (Power BI)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "ab51365054938410990805882a0e9d0e-1814321284.us-east-1.elb.amazonaws.com", descricao: "" },
  { nome: "Instagram Andre Prates", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Certifiquei", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Ideias e Insights", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram IDV", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram LTStocks", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Nesta Casa", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Noticias com Gian", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram PQVNI", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Rodrigo Wainberg", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Team Suno", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "Instagram Tiago Reis US", categoria: "Marketing", tipo: "Passbolt", url: "https://www.instagram.com/", descricao: "" },
  { nome: "PowerBI - OVH", categoria: "Infraestrutura", tipo: "Passbolt", url: "147.135.5.49", descricao: "" },
  { nome: "Servidor Power BI", categoria: "Dados e Analytics", tipo: "Passbolt", url: "ec2-23-23-81-65.compute-1.amazonaws.com", descricao: "" },
  { nome: "Anydesk Eleven - Pago", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://my.anydesk.com/", descricao: "" },
  { nome: "Apollo IO", categoria: "Comercial", tipo: "Passbolt", url: "https://app.apollo.io/", descricao: "" },
  { nome: "B3 SUNO S.A.", categoria: "Financeiro", tipo: "Passbolt", url: "https://onboarding.b3.com.br/", descricao: "" },
  { nome: "Capcut", categoria: "Conteúdo", tipo: "Passbolt", url: "https://www.capcut.com/", descricao: "" },
  { nome: "Chatgpt SEO", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "Claude", categoria: "Outros", tipo: "Passbolt", url: "https://claude.ai/", descricao: "" },
  { nome: "Claude IA.Suno", categoria: "Outros", tipo: "Passbolt", url: "claude.ia", descricao: "" },
  { nome: "Cloudflare fiis", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://dash.cloudflare.com/", descricao: "" },
  { nome: "Correio portal de postagem", categoria: "Outros", tipo: "Passbolt", url: "http://www.portalpostal.com.br/", descricao: "" },
  { nome: "Cursor MAX", categoria: "Desenvolvimento", tipo: "Individual", url: "https://cursor.com/dashboard", descricao: "" },
  { nome: "Devzapp Suno", categoria: "Marketing", tipo: "Passbolt", url: "https://devzapp.com.br/#/login", descricao: "" },
  { nome: "E-mail Área Juridica", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail BIO da Suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail canaisdark@suno.com.br", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "E-mail Compras Suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Contato statusinvest", categoria: "Produtividade", tipo: "Individual", url: "Gmail.com", descricao: "" },
  { nome: "E-mail CRM", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "E-mail ia.suno@suno.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail", descricao: "" },
  { nome: "E-mail Midias Sociais", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "e-mail noreply Suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail nucleo.consultoria@suno.com.br", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "E-mail parceria@suno.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Redes Socias Tiago Reis", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail suporte@fundsexplorer.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Valor em Pauta", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "E-mail Youtube Certifiquei", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Facebook Tiago neutro", categoria: "Marketing", tipo: "Passbolt", url: "facebook.com", descricao: "" },
  { nome: "Facebook Tiago Suno ads", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Gmail e Linkpad - Felipe Tadewald", categoria: "Marketing", tipo: "Passbolt", url: "gmail.com", descricao: "" },
  { nome: "Gmail Tadewald/Twitter", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Growthbook", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://app.growthbook.io/", descricao: "" },
  { nome: "Gtmetrix", categoria: "Outros", tipo: "Passbolt", url: "https://gtmetrix.com/", descricao: "" },
  { nome: "Hostinger", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://hpanel.hostinger.com/", descricao: "" },
  { nome: "inlead", categoria: "Outros", tipo: "Passbolt", url: "https://inlead.digital", descricao: "" },
  { nome: "Intranet Suno", categoria: "Produtividade", tipo: "Individual", url: "https://intranet.suno.com.br/", descricao: "" },
  { nome: "Kabum", categoria: "Operações", tipo: "Passbolt", url: "https://www.kabum.com.br/", descricao: "" },
  { nome: "Linkedin neutro sunobr", categoria: "Marketing", tipo: "Passbolt", url: "https://www.linkedin.com", descricao: "" },
  { nome: "Linkedin Tiago", categoria: "Marketing", tipo: "Passbolt", url: "https://www.linkedin.com", descricao: "" },
  { nome: "Linktree Certifiquei", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Status Invest", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Suno", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Suno Drops - pietro.pasqualotti", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Miro - Conta Paga", categoria: "Produtividade", tipo: "Passbolt", url: "https://miro.com/", descricao: "" },
  { nome: "Miro Asset", categoria: "Produtividade", tipo: "Passbolt", url: "https://miro.com/app/dashboard/", descricao: "" },
  { nome: "Notion", categoria: "Produtividade", tipo: "Passbolt", url: "https://www.notion.so/", descricao: "" },
  { nome: "Notion Midias Sociais", categoria: "Produtividade", tipo: "Passbolt", url: "https://www.notion.so/", descricao: "" },
  { nome: "Portal Eleven - Time Advisory", categoria: "Produto", tipo: "Passbolt", url: "https://portal.elevenfinancial.com/auth", descricao: "" },
  { nome: "Power BI - Conta da Gestora", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://admin.microsoft.com/#/users", descricao: "" },
  { nome: "Stape IO", categoria: "Marketing", tipo: "Passbolt", url: "https://app.stape.io/dashboard", descricao: "" },
  { nome: "Vercel Consultoria", categoria: "Outros", tipo: "Passbolt", url: "https://vercel.com/new", descricao: "" },
  { nome: "Vercel Suno", categoria: "Outros", tipo: "Passbolt", url: "https://vercel.com/signup", descricao: "" },
  { nome: "Youtube Tiago", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Algar - Área do cliente", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://loja.algar.com.br/account", descricao: "" },
  { nome: "Anydesk TV Research", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Asset LLM OpenAI", categoria: "Produtividade", tipo: "Passbolt", url: "https://platform.openai.com/", descricao: "" },
  { nome: "AWS Suno POC", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com", descricao: "" },
  { nome: "Azure StatusInvest", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Base44", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://app.base44.com/", descricao: "" },
  { nome: "Bitly Softwares", categoria: "Marketing", tipo: "Passbolt", url: "https://app.bitly.com/settings/organization/Ol46exz1XCn/details/billing/", descricao: "" },
  { nome: "BTG Developer", categoria: "Financeiro", tipo: "Passbolt", url: "https://developer-partner.btgpactual.com/login", descricao: "" },
  { nome: "Chat GPT Compliance", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "Chat GPT Social Selling", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "ChatGPT Mídias", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "ChatGPT Sales Advisory", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "CVM", categoria: "Jurídico", tipo: "Passbolt", url: "https://www.rad.cvm.gov.br/enet/", descricao: "" },
  { nome: "E-mail dados backoffice services", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail e Chatgpt atendimento@statusinvest.com.br", categoria: "Produtividade", tipo: "Passbolt", url: "gmail.com", descricao: "" },
  { nome: "E-mail Marketing Status Invest", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail materialcontadora@gmail.com", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail sucessodocliente@sunoresearch.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "ElevenLabs Suno", categoria: "Conteúdo", tipo: "Passbolt", url: "https://elevenlabs.io/", descricao: "" },
  { nome: "Email Suno Asset", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Envato Elements", categoria: "Design", tipo: "Passbolt", url: "https://elements.envato.com/pt-br/", descricao: "" },
  { nome: "Facebook Meta Business Manager", categoria: "Marketing", tipo: "Passbolt", url: "https://business.facebook.com/latest/settings", descricao: "" },
  { nome: "Funnelytics", categoria: "Marketing", tipo: "Passbolt", url: "https://funnelytics.io/", descricao: "" },
  { nome: "Funnelytics Softwares", categoria: "Marketing", tipo: "Passbolt", url: "https://hub.funnelytics.io/", descricao: "" },
  { nome: "Funnelytics Softwares old", categoria: "Marketing", tipo: "Passbolt", url: "https://hub.funnelytics.io/c/hub-tour", descricao: "" },
  { nome: "GreatPages", categoria: "Marketing", tipo: "Passbolt", url: "https://www.greatpages.com.br/", descricao: "" },
  { nome: "greatpages Bruna Dias", categoria: "Marketing", tipo: "Passbolt", url: "https://app.greatpages.com.br/dominios", descricao: "" },
  { nome: "Hotjar ADM Eleven", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://insights.hotjar.com/", descricao: "" },
  { nome: "Lovable Consultoria", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://lovable.dev/", descricao: "" },
  { nome: "LucidChart", categoria: "Produtividade", tipo: "Passbolt", url: "https://lucid.app/documents#/dashboard", descricao: "" },
  { nome: "Miro CRM", categoria: "Produtividade", tipo: "Passbolt", url: "miro.com", descricao: "" },
  { nome: "N8N Asset", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://assetsuno.app.n8n.cloud/d004191c87db645872b57e8076cd8436618a2c9f2e2eb796bacd2cbdc9932e43", descricao: "" },
  { nome: "N8N Automação", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://n8n-n8n.qldo4p.easypanel.host/", descricao: "" },
  { nome: "Plugify aluguel notebooks", categoria: "RH", tipo: "Passbolt", url: "https://galiplugify.com.br/admin", descricao: "" },
  { nome: "Portal Eleven - Time Asset", categoria: "Produto", tipo: "Passbolt", url: "https://portal.elevenfinancial.com/", descricao: "" },
  { nome: "Portal Eleven - Time Research", categoria: "Produto", tipo: "Passbolt", url: "https://portal.elevenfinancial.com/", descricao: "" },
  { nome: "Power BI Analise", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://app.powerbi.com/home", descricao: "" },
  { nome: "Power BI Negocios", categoria: "Dados e Analytics", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Qdrant", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://qdrant.tech/", descricao: "" },
  { nome: "Registro.br Tiago Reis", categoria: "Infraestrutura", tipo: "Passbolt", url: "registro.br", descricao: "" },
  { nome: "Registro.br TIREI31 sunoresearch.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "regsitro.br", descricao: "" },
  { nome: "Sendgrid Eleven - Twilio Cloud", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://app.sendgrid.com/", descricao: "" },
  { nome: "Snowflake ASSET", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://wbb32105.us-east-1.snowflakecomputing.com", descricao: "" },
  { nome: "Soundcloud.com - Eleven", categoria: "Conteúdo", tipo: "Passbolt", url: "https://soundcloud.com/discover", descricao: "" },
  { nome: "Status Invest - XP licenças BHS suporte", categoria: "Produto", tipo: "Passbolt", url: "https://portal.bhs.com.br/usuarios", descricao: "" },
  { nome: "Twilio WhatsApp API", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://console.twilio.com/account/plans", descricao: "" },
  { nome: "Twitter Vitor Duarte", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Typeform Suno", categoria: "Marketing", tipo: "Passbolt", url: "https://admin.typeform.com/accounts/01D8JVCX6ED8FXRVNPE9QFPEW0/plan", descricao: "" },
  { nome: "Vivo Gestor Telefonia", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://mve.vivo.com.br/sec/dashboard", descricao: "" },
  { nome: "VTurb", categoria: "Conteúdo", tipo: "Passbolt", url: "https://app.vturb.com/folders", descricao: "" },
  { nome: "Wordpress Gaia Suno", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://gaia.suno.com.br/wp-login.php", descricao: "" },
  { nome: "ACF - Advanced Custom Fields", categoria: "Outros", tipo: "Passbolt", url: "https://www.advancedcustomfields.com/", descricao: "" },
  { nome: "Adobe sunoresearch@gmail - Não é admin", categoria: "Design", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "airflow v2", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://airflow-v2-3438dd66106286d7.suno.com.br", descricao: "" },
  { nome: "anbima developers", categoria: "Financeiro", tipo: "Passbolt", url: "https://admin-developers.anbima.com.br/api-portal/user", descricao: "" },
  { nome: "App Store Connect", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://appstoreconnect.apple.com/login", descricao: "" },
  { nome: "Bitrise for suno.softwares", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://app.bitrise.io/dashboard", descricao: "" },
  { nome: "browserstack softwares", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://live.browserstack.com/", descricao: "" },
  { nome: "Buzzlead", categoria: "Marketing", tipo: "Passbolt", url: "https://app.buzzlead.com.br/", descricao: "" },
  { nome: "Canva", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Chat GPT Comercial", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "Chat GPT Eventos", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "ChatGPT - Cultura e Desenvolvimento", categoria: "Produtividade", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "ChatGPT Asset", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "ChatGPT Criação MKT", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "ChatGPT CRM", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "Chatgpt IA API - Time TI", categoria: "Produtividade", tipo: "Passbolt", url: "https://platform.openai.com/", descricao: "" },
  { nome: "Chatgpt Softwares - Adm plano corporativo", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "Chatgpt Softwares - Time IA Suno", categoria: "Produtividade", tipo: "Passbolt", url: "https://chatgpt.com/", descricao: "" },
  { nome: "Claro Status Invest", categoria: "Produto", tipo: "Passbolt", url: "app minha claro residencial", descricao: "" },
  { nome: "CoinMarket Cap", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://pro.coinmarketcap.com/account/plan", descricao: "" },
  { nome: "Cursor", categoria: "Desenvolvimento", tipo: "Individual", url: "https://www.cursor.com/", descricao: "" },
  { nome: "E-mail Gmail solucoes.investimento@suno.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail integracoesia", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail midias pagas.", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "ELEVEN - Cloudflare", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://dash.cloudflare.com/login", descricao: "" },
  { nome: "Eleven plataforma multichanel 11pro", categoria: "Marketing", tipo: "Passbolt", url: "https://11pro.com.br/app/admin/users", descricao: "" },
  { nome: "Envato themeforest", categoria: "Design", tipo: "Passbolt", url: "https://elements.envato.com/pt-br/?_ga=2.13005557.371456652.1702907695-1337997869.1696366470", descricao: "" },
  { nome: "Figma Design", categoria: "Design", tipo: "Passbolt", url: "https://www.figma.com/files", descricao: "" },
  { nome: "Figma Devs Tech", categoria: "Design", tipo: "Passbolt", url: "https://www.figma.com/", descricao: "" },
  { nome: "Figma SEO", categoria: "Design", tipo: "Passbolt", url: "https://www.figma.com/", descricao: "" },
  { nome: "Figma Status Invest", categoria: "Design", tipo: "Passbolt", url: "https://www.figma.com", descricao: "" },
  { nome: "Gamma IA", categoria: "Produtividade", tipo: "Passbolt", url: "https://gamma.app/", descricao: "" },
  { nome: "github softwares atual", categoria: "Desenvolvimento", tipo: "Individual", url: "https://github.com/suno-research", descricao: "" },
  { nome: "Google Flow", categoria: "Outros", tipo: "Passbolt", url: "https://labs.google/flow/", descricao: "" },
  { nome: "icloud apple iphone 14 Midias Socias", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://account.apple.com/account/manage", descricao: "" },
  { nome: "Intranet para Eleven e Assessoria Status Invest", categoria: "Produtividade", tipo: "Individual", url: "https://intranet.suno.com.br", descricao: "" },
  { nome: "Kubecost Cloud", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://app.kubecost.com/", descricao: "" },
  { nome: "LeadPages Eleven", categoria: "Marketing", tipo: "Passbolt", url: "https://my.leadpages.com/#/pages", descricao: "" },
  { nome: "Lovable", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://lovable.dev/", descricao: "" },
  { nome: "Meetrox", categoria: "Comunicação", tipo: "Passbolt", url: "https://meetrox.ai/", descricao: "" },
  { nome: "Microsoft Bing Ads Midias Pagas", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "N8n", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://iasuno.app.n8n.cloud/", descricao: "" },
  { nome: "NPMJS", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://www.npmjs.com/", descricao: "" },
  { nome: "Outlook Assessoria Closer@statusinvest.com", categoria: "Produtividade", tipo: "Individual", url: "https://outlook.office.com/mail/", descricao: "" },
  { nome: "Rebrandly encurtador de link", categoria: "Marketing", tipo: "Passbolt", url: "https://www.rebrandly.com/", descricao: "" },
  { nome: "semrush softwares@", categoria: "Marketing", tipo: "Passbolt", url: "https://pt.semrush.com/projects/", descricao: "" },
  { nome: "sentry dev", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://suno-w0.sentry.io/", descricao: "" },
  { nome: "Servidor OVH Nexxus HOMOLOGACAO", categoria: "Infraestrutura", tipo: "Passbolt", url: "40.160.29.93", descricao: "" },
  { nome: "snowflake", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://app.snowflake.com/qeylctm/xgb98696", descricao: "" },
  { nome: "Social Blade", categoria: "Marketing", tipo: "Passbolt", url: "https://socialblade.com/login", descricao: "" },
  { nome: "Status Invest - Switch 48P1", categoria: "Produto", tipo: "Passbolt", url: "http://10.12.7.218/", descricao: "" },
  { nome: "Suno Research GPT 1", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "Suno Research GPT 2", categoria: "Produtividade", tipo: "Passbolt", url: "chatgpt.com", descricao: "" },
  { nome: "Tiktok midias pagas", categoria: "Marketing", tipo: "Passbolt", url: "https://www.tiktok.com/", descricao: "" },
  { nome: "Tiktok Status Invest", categoria: "Marketing", tipo: "Passbolt", url: "tiktok.com", descricao: "" },
  { nome: "VideoGen", categoria: "Conteúdo", tipo: "Passbolt", url: "https://videogen.io/", descricao: "" },
  { nome: "Vivo Plataforma Licenças MS", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://www.vivoplataformadigital.com.br", descricao: "" },
  { nome: "Webflow - Google Login", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://webflow.com/dashboard", descricao: "" },
  { nome: "Wordpress assessoria.statusinvest.com.br", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://assessoria.statusinvest.com.br/wp-admin", descricao: "" },
  { nome: "Zapier - Oficial", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Zapier (desativado)", categoria: "Outros", tipo: "Passbolt", url: "https://zapier.com/", descricao: "" },
  { nome: "addevent inbound@sunoresearch.com.br", categoria: "Produtividade", tipo: "Passbolt", url: "https://app.addevent.com/users", descricao: "" },
  { nome: "advanced custom fields", categoria: "Outros", tipo: "Passbolt", url: "https://www.advancedcustomfields.com/", descricao: "" },
  { nome: "AWS - Ingram - Organization Root", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://suno-psa.signin.aws.amazon.com/console", descricao: "" },
  { nome: "AWS - root - aws.audit@suno.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.data@suno.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.dev@statusinvest.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.dev@suno.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.log@suno.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.master@fiis.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.master@statusinvest.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.staging@fiis.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.staging@statusinvest.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - aws.staging@suno.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - carlos.ribeiro+teste2@sunoresearch.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "AWS - root - sunocore@sunoresearch.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://signin.aws.amazon.com/", descricao: "" },
  { nome: "Clarity grupo Suno", categoria: "Outros", tipo: "Passbolt", url: "https://clarity.microsoft.com/projects", descricao: "" },
  { nome: "Cloudflare Suno", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://dash.cloudflare.com/dcdeb7f3a6717f158f95dd72934523d1/billing", descricao: "" },
  { nome: "Creatopy", categoria: "Outros", tipo: "Passbolt", url: "https://www.creatopy.com/", descricao: "" },
  { nome: "E-mail Analistas", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail pagamentos", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Softwares Suno", categoria: "Produtividade", tipo: "Individual", url: "https://accounts.google.com/", descricao: "" },
  { nome: "E-mail suporte@statusinvest.com Gmail Google", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "Facebook Eleven", categoria: "Marketing", tipo: "Passbolt", url: "www.facebook.com.br", descricao: "" },
  { nome: "Github Softwares", categoria: "Desenvolvimento", tipo: "Individual", url: "https://github.com", descricao: "" },
  { nome: "Grafana", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://grafana-xi38wil8duw7er41.statusinvest.com.br/login", descricao: "" },
  { nome: "Grafana - Staging - Suno", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://staging-grafana-d9c0e52dd1.suno.com.br", descricao: "" },
  { nome: "heavyhost", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://customer.heavyhost.com.br/index.php", descricao: "" },
  { nome: "Hotmart Suno e Status Invest", categoria: "Financeiro", tipo: "Passbolt", url: "https://app-vlc.hotmart.com/login", descricao: "" },
  { nome: "JWPlayer", categoria: "Outros", tipo: "Passbolt", url: "dashboard.jwplayer.com", descricao: "" },
  { nome: "Kangu", categoria: "Operações", tipo: "Passbolt", url: "https://portal.kangu.com.br/onboarding", descricao: "" },
  { nome: "lalamove", categoria: "Operações", tipo: "Passbolt", url: "https://web.lalamove.com/login", descricao: "" },
  { nome: "Linktree Telegram Assinantes", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Vitor Duarte", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/vitorlopesduarte", descricao: "" },
  { nome: "Looom - Time Cursos", categoria: "Outros", tipo: "Passbolt", url: "https://www.loom.com/", descricao: "" },
  { nome: "LSEG API", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://apidocs.refinitiv.com/Apps/ApiDocs", descricao: "" },
  { nome: "Microsoft Azure", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://portal.azure.com", descricao: "" },
  { nome: "Nova Laravel", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://nova.laravel.com/", descricao: "" },
  { nome: "OpenMetadata", categoria: "Dados e Analytics", tipo: "Passbolt", url: "http://15.204.214.98:8585", descricao: "" },
  { nome: "OVH Status - Vazio", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://us.ovhcloud.com/manager/#/hub/", descricao: "" },
  { nome: "OVH storage suno-data-ia [Read Only]", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "OVH Storage suno-data-mart [Read Only]", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://s3.us-east-va.perf.cloud.ovh.us", descricao: "" },
  { nome: "PagerDuty", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://sunoresearch.pagerduty.com/", descricao: "" },
  { nome: "PandaDoc", categoria: "Jurídico", tipo: "Passbolt", url: "https://www.pandadoc.com/", descricao: "" },
  { nome: "Pipefy Admin", categoria: "Produtividade", tipo: "Passbolt", url: "https://app.pipefy.com/organizations/238512", descricao: "" },
  { nome: "Pipefy Dados", categoria: "Produtividade", tipo: "Passbolt", url: "https://app-auth.pipefy.com/login?afterLoginRedirectTo=https%3A%2F%2Fapp.pipefy.com%2Fpipes%2F301438263", descricao: "" },
  { nome: "Postgrain", categoria: "Marketing", tipo: "Passbolt", url: "https://postgrain.com", descricao: "" },
  { nome: "Supermetrics", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://hub.supermetrics.com/landing/storage", descricao: "" },
  { nome: "Supermetrics API", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://api.supermetrics.com/enterprise/v2/query", descricao: "" },
  { nome: "Suporte Audere - firewall", categoria: "Outros", tipo: "Passbolt", url: "https://audere.desk.ms/?LoginPortal", descricao: "" },
  { nome: "Twilio Authy comparilhado", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://authy.com/download/", descricao: "" },
  { nome: "Twitter FundsExplorer", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/FundsExplorer", descricao: "" },
  { nome: "UpLexis", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://login.uplexis.com/login", descricao: "" },
  { nome: "Uptimerobot", categoria: "Infraestrutura", tipo: "Passbolt", url: "uptimerobot.com", descricao: "" },
  { nome: "US OVH- Cloud", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://us.ovhcloud.com/manager/#/dedicated/useraccount/users", descricao: "" },
  { nome: "Vimeo Area de Assinante", categoria: "Conteúdo", tipo: "Passbolt", url: "https://vimeo.com", descricao: "" },
  { nome: "Youtube Eleven", categoria: "Conteúdo", tipo: "Passbolt", url: "www.youtube.com", descricao: "" },
  { nome: "yup chat", categoria: "Atendimento", tipo: "Passbolt", url: "https://app.yup.chat/", descricao: "" },
  { nome: "Zoom Eleven", categoria: "Comunicação", tipo: "Passbolt", url: "www.zoom.com.br", descricao: "" },
  { nome: "Admin Microsoft Office 365", categoria: "Outros", tipo: "Passbolt", url: "https://admin.microsoft.com/Adminportal/Home#", descricao: "" },
  { nome: "AdOpt", categoria: "Outros", tipo: "Passbolt", url: "https://dash.goadopt.io/organizations", descricao: "" },
  { nome: "Airflow (Infra)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://airflow-wkq9mkyojr9w8n70.suno.com.br", descricao: "" },
  { nome: "Algar Telecom Gerencia de Redes", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://www.algartelecom.com.br/gerenciaderede/", descricao: "" },
  { nome: "Amazon AWS", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://917132443740.signin.aws.amazon.com/console", descricao: "" },
  { nome: "Antigo gsuite suporte@fundsexplorer.com.br", categoria: "Produto", tipo: "Passbolt", url: "https://admin.google.com/", descricao: "" },
  { nome: "AnyDesk - OnePage", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "B3 developers", categoria: "Financeiro", tipo: "Passbolt", url: "https://clientes.b3.com.br/pt_br/atendimento/", descricao: "" },
  { nome: "Braintree Gateway Paypal Carlos Ribeiro", categoria: "Financeiro", tipo: "Passbolt", url: "https://www.braintreegateway.com/", descricao: "" },
  { nome: "ChatGPT", categoria: "Produtividade", tipo: "Passbolt", url: "https://chat.openai.com/auth/login", descricao: "" },
  { nome: "ChatGPT Jurídico", categoria: "Produtividade", tipo: "Passbolt", url: "https://chat.openai.com/", descricao: "" },
  { nome: "cma.com.br", categoria: "Outros", tipo: "Passbolt", url: "https://portaldocliente.cma.com.br/index?menu=painel", descricao: "" },
  { nome: "Data Team - Somente Leitura", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "E-mail Contato Suno", categoria: "Produtividade", tipo: "Individual", url: "google.com", descricao: "" },
  { nome: "E-mail contato@fiis.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail para automação do Monday", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail PCzinho da sala de reunião. Logitech", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Simpatio Odonto", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Suporte Fundsexplorer", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail Tiago Reis", categoria: "Produtividade", tipo: "Individual", url: "conectado no hubspot", descricao: "" },
  { nome: "E-mail TVs Sede Suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Email - Afiliados Suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Email Design", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Evermart Checkout", categoria: "Outros", tipo: "Passbolt", url: "https://dashboard.mycheckout.com.br/login", descricao: "" },
  { nome: "Forticloud Firewall Suno", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://support.fortinet.com/Download/FirmwareImages.aspx", descricao: "" },
  { nome: "Google Gmail Backoffice", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Gráficos Mundivox link Suno", categoria: "Outros", tipo: "Passbolt", url: "https://graficos.mundivox.com/Login", descricao: "" },
  { nome: "Hotmart Suporte Funds Explorer", categoria: "Financeiro", tipo: "Passbolt", url: "https://app.hotmart.com", descricao: "" },
  { nome: "INCSUBFEE wpmudev", categoria: "Outros", tipo: "Passbolt", url: "https://wpmudev.com/login/?", descricao: "" },
  { nome: "Linktree Suno Asset", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/admin/", descricao: "" },
  { nome: "Miro Suno e FundsExplorer", categoria: "Produtividade", tipo: "Passbolt", url: "https://miro.com/app/settings/team/3074457354995769141/users", descricao: "" },
  { nome: "Monitoramento Audere zabbix", categoria: "Outros", tipo: "Passbolt", url: "http://zabbix.audere.com.br/", descricao: "" },
  { nome: "MySQL - suno_analytics_wp - staging", categoria: "Outros", tipo: "Passbolt", url: "mysql_staging_7wspceyu32wtn07w.suno.com.br", descricao: "" },
  { nome: "New Relic Softwares", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://newrelic.com/", descricao: "" },
  { nome: "OneSignal - Plano atual Free", categoria: "Marketing", tipo: "Passbolt", url: "https://app.onesignal.com/login", descricao: "" },
  { nome: "Onesignal Plano atual Free", categoria: "Marketing", tipo: "Passbolt", url: "https://onesignal.com/", descricao: "" },
  { nome: "Outgrow", categoria: "Outros", tipo: "Passbolt", url: "https://sunoresearch289.outgrow.co/settings/membership", descricao: "" },
  { nome: "OVH Gestora", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://us.ovhcloud.com/auth/?onsuccess=https%3A//us.ovhcloud.com/manager&ovhSubsidiary=US", descricao: "" },
  { nome: "Portal Unifi Ubiquiti Suno", categoria: "Infraestrutura", tipo: "Passbolt", url: "ui.com", descricao: "" },
  { nome: "Rocket.Chat", categoria: "Comunicação", tipo: "Passbolt", url: "https://rocketchat.suno.com.br/", descricao: "" },
  { nome: "S.Invest - Conta Intelbras Camera", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://idp.conta.intelbras.com", descricao: "" },
  { nome: "S.Invest Expo", categoria: "Outros", tipo: "Passbolt", url: "https://expo.dev/accounts/statusinvest", descricao: "" },
  { nome: "S.Invest Security ScoreCard", categoria: "Outros", tipo: "Passbolt", url: "https://platform.securityscorecard.io/#/scorecard/statusinvest.com.br/factors", descricao: "" },
  { nome: "Security ScoreCard", categoria: "Outros", tipo: "Passbolt", url: "https://platform.securityscorecard.io/#/scorecard/suno.com.br/issues/OPEN", descricao: "" },
  { nome: "Sendgrid", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://sendgrid.com", descricao: "" },
  { nome: "Servidor OVH Windows Nexxus", categoria: "Infraestrutura", tipo: "Passbolt", url: "15.204.162.156", descricao: "" },
  { nome: "sleuth", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://app.sleuth.io/", descricao: "" },
  { nome: "Suno - Conta Intelbras", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://portal.conta.intelbras.com/", descricao: "" },
  { nome: "Vimeo pagamentos invoices", categoria: "Conteúdo", tipo: "Passbolt", url: "https://billing-account.vimeo.com/portal/viewAllInvoices", descricao: "" },
  { nome: "Vivo - Internet da Status Invest", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://mve.vivo.com.br/", descricao: "" },
  { nome: "WOOCOMMERCE suno tech", categoria: "Outros", tipo: "Passbolt", url: "https://woocommerce.com/my-dashboard/", descricao: "" },
  { nome: "wordpress lp.suno.com.br", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://lp.suno.com.br/wp-admin", descricao: "" },
  { nome: "Youtube e-mail Area assinantes", categoria: "Conteúdo", tipo: "Passbolt", url: "youtube.com", descricao: "" },
  { nome: "Youtube Prof Baroni", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Youtube Suno Noticias", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Adobe admin softwares", categoria: "Design", tipo: "Passbolt", url: "https://adminconsole.adobe.com/1EF51EAD61F2A9D60A495F85@AdobeOrg/users", descricao: "" },
  { nome: "Adobe Design midiassociais", categoria: "Design", tipo: "Passbolt", url: "https://account.adobe.com/", descricao: "" },
  { nome: "Adobe licenças", categoria: "Design", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Adobe Suite - Conta Admin", categoria: "Design", tipo: "Passbolt", url: "https://adminconsole.adobe.com/", descricao: "" },
  { nome: "API - Status Invest (ETFS)", categoria: "Produto", tipo: "Passbolt", url: "https://marketdata.statusinvest.com.br/api/v1/InternacionalEtf/resume/[ETF]", descricao: "" },
  { nome: "Atlassian Jira", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://id.atlassian.com/login", descricao: "" },
  { nome: "AWS Athena", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Bitly Suno Research", categoria: "Marketing", tipo: "Passbolt", url: "bitly.com", descricao: "" },
  { nome: "braintree gateway softwares", categoria: "Financeiro", tipo: "Passbolt", url: "https://www.braintreegateway.com", descricao: "" },
  { nome: "Browserless", categoria: "Outros", tipo: "Passbolt", url: "https://cloud.browserless.io/account/", descricao: "" },
  { nome: "Claro - Internet Sede", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://minhaclaroresidencial.claro.com.br/public", descricao: "" },
  { nome: "Coinbase", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://www.coinbase.com/home", descricao: "" },
  { nome: "databox", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://app.databox.com/login", descricao: "" },
  { nome: "DevZap", categoria: "Marketing", tipo: "Passbolt", url: "https://devzapp.com.br/#/dashboard", descricao: "" },
  { nome: "Dremio (Infra)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://dremio-2mvj4w04rnzorb2xnk71r945ja6h5nbd.suno.com.br", descricao: "" },
  { nome: "Dremio (NiFi)", categoria: "Dados e Analytics", tipo: "Passbolt", url: "jdbc:dremio:direct=internal-a8a9e7c52eebc43139a811dbdf19c932-375480515.us-east-1.elb.amazonaws.com:31010;", descricao: "" },
  { nome: "Dremio v2 OVH", categoria: "Infraestrutura", tipo: "Passbolt", url: "http://dremio-v2-u2esky1sdn3pwvck.suno.com.br/", descricao: "" },
  { nome: "E-mail contato@certifiquei.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail contato@simpatio.com.br", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Figma Edu rodrigues", categoria: "Design", tipo: "Passbolt", url: "https://www.figma.com/", descricao: "" },
  { nome: "Figma Lucas Oliveira", categoria: "Design", tipo: "Passbolt", url: "figma.com", descricao: "" },
  { nome: "Godaddy", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://account.godaddy.com/products", descricao: "" },
  { nome: "Heroku Suno", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://id.heroku.com/login", descricao: "" },
  { nome: "Hotjar ADM", categoria: "Dados e Analytics", tipo: "Passbolt", url: "https://insights.hotjar.com/", descricao: "" },
  { nome: "Instagram FIIs.com.br2", categoria: "Marketing", tipo: "Passbolt", url: "intagram.com", descricao: "" },
  { nome: "Iugu", categoria: "Financeiro", tipo: "Passbolt", url: "https://alia.iugu.com/", descricao: "" },
  { nome: "KDP Amazon", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://kdp.amazon.com/", descricao: "" },
  { nome: "Linktree Marcos", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Magazine Luiza", categoria: "Operações", tipo: "Passbolt", url: "https://www.magazineluiza.com.br/", descricao: "" },
  { nome: "manychat", categoria: "Marketing", tipo: "Passbolt", url: "https://manychat.com/", descricao: "" },
  { nome: "Norton senha padrão", categoria: "Outros", tipo: "Passbolt", url: "https://login.norton.com/sso/embedded/update", descricao: "" },
  { nome: "OVH SUNO FINANCEIRO", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://us.ovhcloud.com/manager/#/hub", descricao: "" },
  { nome: "podcasters spotify", categoria: "Conteúdo", tipo: "Passbolt", url: "https://podcasters.spotify.com/", descricao: "" },
  { nome: "Registro.br - SUNO S.A.", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://registro.br", descricao: "" },
  { nome: "Sendgrid fiis.com.br", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://app.sendgrid.com/", descricao: "" },
  { nome: "Sentry", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://sentry.io/", descricao: "" },
  { nome: "Servidor OVH Windows StatusInvest", categoria: "Infraestrutura", tipo: "Passbolt", url: "15.204.162.17", descricao: "" },
  { nome: "Soundcloud", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "StatusInvest Assessoria", categoria: "Produto", tipo: "Passbolt", url: "https://staging-assessoria-44httv1l914jg7xv.statusinvest.com.br/wp-admin/", descricao: "" },
  { nome: "Twitch Tiago", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Unifi ubiquiti OS Cloud Key", categoria: "Infraestrutura", tipo: "Passbolt", url: "http://172.18.10.10", descricao: "" },
  { nome: "VideoScribe Sparkol", categoria: "Outros", tipo: "Passbolt", url: "https://www.videoscribe.co/en/login/", descricao: "" },
  { nome: "Voip Vono", categoria: "Outros", tipo: "Passbolt", url: "https://meuvono.falevono.com.br/entrar", descricao: "" },
  { nome: "wisepops", categoria: "Outros", tipo: "Passbolt", url: "wisepops.com/login", descricao: "" },
  { nome: "wordpress woocommerce", categoria: "Desenvolvimento", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Youtube Fundsexplorer", categoria: "Conteúdo", tipo: "Passbolt", url: "https://myaccount.google.com/brandaccounts/112478983510730149112/view?rapt=AEjHL4N_VQ7tLK_icMxy6CIniooCjXtxo7VVWWJfTC8yN1KwBCsW5ihArKVW6uhVT4GbMxkJqzcEp-Z-TLxSVTtHuWExBUkMEw", descricao: "" },
  { nome: "YouTube Suno Educação", categoria: "Conteúdo", tipo: "Passbolt", url: "https://myaccount.google.com/brandaccounts/113170896363249978955/view?pli=1&rapt=AEjHL4NmglBc5dYQpLp4JB49P_RkRlogztJdBJ6B-EtD9Pr6yjpOKBTfdpU2kfSPpHYpwaYAv3hlVNx8IkgC4ZLd3yTBq18hrw", descricao: "" },
  { nome: "ActiveCampaign Certifiquei", categoria: "Marketing", tipo: "Passbolt", url: "https://certifiquei.activehosted.com/", descricao: "" },
  { nome: "Agro20", categoria: "Outros", tipo: "Passbolt", url: "https://agro20.com.br/wp-admin/", descricao: "" },
  { nome: "Alexa", categoria: "Outros", tipo: "Passbolt", url: "https://alexa.amazon.com", descricao: "" },
  { nome: "BItly suno", categoria: "Marketing", tipo: "Passbolt", url: "bitly.com", descricao: "" },
  { nome: "Bizagi", categoria: "Outros", tipo: "Passbolt", url: "https://portal.bizagi.com/", descricao: "" },
  { nome: "BugsNag", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://www.bugsnag.com/", descricao: "" },
  { nome: "Certifiquei pdpe", categoria: "Produto", tipo: "Passbolt", url: "https://www.certifiquei.com.br/cursos/pdpe/", descricao: "" },
  { nome: "Certifiquei.com.br", categoria: "Produto", tipo: "Passbolt", url: "certifiquei.com.br/wp-admin", descricao: "" },
  { nome: "Compras Mercado Livre", categoria: "Comercial", tipo: "Passbolt", url: "mercadolivre.com.br", descricao: "" },
  { nome: "Conecta Bio Suno", categoria: "Outros", tipo: "Passbolt", url: "https://conectabem.com/app/sites", descricao: "" },
  { nome: "Contadoradabolsa.com.br", categoria: "Outros", tipo: "Passbolt", url: "contadoradabolsa.com.br/wp-admin", descricao: "" },
  { nome: "Cpfcnpj.com.br", categoria: "Outros", tipo: "Passbolt", url: "cpfcnpj.com.br", descricao: "" },
  { nome: "Crip", categoria: "Outros", tipo: "Passbolt", url: "https://app.crisp.chat/", descricao: "" },
  { nome: "Crisp.chat", categoria: "Atendimento", tipo: "Passbolt", url: "https://app.crisp.chat/", descricao: "" },
  { nome: "DISQUS", categoria: "Outros", tipo: "Passbolt", url: "https://disqus.com/profile/login/", descricao: "" },
  { nome: "Elementor", categoria: "Outros", tipo: "Passbolt", url: "https://my.elementor.com/login/?redirect_to=%2F", descricao: "" },
  { nome: "Email - Afiliados Certifiquei", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Email - Contato", categoria: "Produtividade", tipo: "Individual", url: "gmail.com.br", descricao: "" },
  { nome: "ereader-wp", categoria: "Outros", tipo: "Passbolt", url: "https://ereader-wp-r7vi128733m0i6qp.suno.com.br/", descricao: "" },
  { nome: "Fastlane Match Decrypt Repository", categoria: "Outros", tipo: "Passbolt", url: "https://gitlab.com/suno-squad-app/fastlane-ios-certificates", descricao: "" },
  { nome: "FIIs.com.br", categoria: "Outros", tipo: "Passbolt", url: "https://whm.fiis.com.br/", descricao: "" },
  { nome: "Forncedor XP", categoria: "Outros", tipo: "Passbolt", url: "https://xpinc.capworkflow.com/SignIn.aspx", descricao: "" },
  { nome: "Fortigate Fortinet Cloud", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://support.fortinet.com/welcome/#/", descricao: "" },
  { nome: "Fusion charts", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://puc.fusioncharts.com/RegisterAction.asp?Email=softwares%40sunoresearch.com.br&submit=Sign+Up", descricao: "" },
  { nome: "Gmail Jessica Dias", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Gmail Telegram", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "Google Play Store", categoria: "Outros", tipo: "Passbolt", url: "https://play.google.com/console/u/0/developers/6297224382812498638/app/4975966312160141735/user-feedback/reviews", descricao: "" },
  { nome: "Help Scout", categoria: "Atendimento", tipo: "Passbolt", url: "https://secure.helpscout.net/", descricao: "" },
  { nome: "Hubspot", categoria: "Comercial", tipo: "Passbolt", url: "https://app.hubspot.com/settings/7171354/users", descricao: "" },
  { nome: "Lenovo Compras", categoria: "Operações", tipo: "Passbolt", url: "https://www.lenovo.com/br/", descricao: "" },
  { nome: "Linktree Waka", categoria: "Marketing", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Lp.certifiquei.com.br", categoria: "Produto", tipo: "Passbolt", url: "lp.certifiquei.com.br", descricao: "" },
  { nome: "Lp.fiis.com.br", categoria: "Outros", tipo: "Passbolt", url: "lp.fiis.com.br/wp-admin", descricao: "" },
  { nome: "Lp.fundsexplorer.com.br", categoria: "Produto", tipo: "Passbolt", url: "lp.fundsexplorer.com.br/wp-admin", descricao: "" },
  { nome: "Market Stack", categoria: "Outros", tipo: "Passbolt", url: "https://marketstack.com/login", descricao: "" },
  { nome: "Mercado Pago", categoria: "Financeiro", tipo: "Passbolt", url: "https://www.mercadopago.com.br/", descricao: "" },
  { nome: "Metabase", categoria: "Dados e Analytics", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Monday", categoria: "Produtividade", tipo: "Individual", url: "https://suno-research.monday.com/", descricao: "" },
  { nome: "Monitoramento Audere Grafana", categoria: "Infraestrutura", tipo: "Passbolt", url: "http://zabbix.audere.com.br:3000/d/BnVC6SWVk/audere-suno-cliente-final?orgId=1&refresh=5s&kiosk", descricao: "" },
  { nome: "Montserratholdings", categoria: "Outros", tipo: "Passbolt", url: "https://montserratholdings.com.br/wp-admin", descricao: "" },
  { nome: "NewRelic", categoria: "Infraestrutura", tipo: "Passbolt", url: "newrelic.com", descricao: "" },
  { nome: "Outline Compartilhado", categoria: "Produtividade", tipo: "Passbolt", url: "https://sunoresearch.getoutline.com", descricao: "" },
  { nome: "Pipefy Compliance", categoria: "Produtividade", tipo: "Passbolt", url: "https://app.pipefy.com/organizations/238512", descricao: "" },
  { nome: "Pipefy growth", categoria: "Produtividade", tipo: "Passbolt", url: "https://app.pipefy.com/organizations/238512", descricao: "" },
  { nome: "Porquevocenaoinveste.com.br", categoria: "Outros", tipo: "Passbolt", url: "https://porquevocenaoinveste.com.br/wp-login.php", descricao: "" },
  { nome: "powerbi ovh", categoria: "Infraestrutura", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Pusher.com", categoria: "Outros", tipo: "Passbolt", url: "pusher.com", descricao: "" },
  { nome: "Reetro", categoria: "Outros", tipo: "Passbolt", url: "https://www.reetro.app/", descricao: "" },
  { nome: "Scaleway", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://console.online.net/", descricao: "" },
  { nome: "Simpatio.com.br", categoria: "Outros", tipo: "Passbolt", url: "simpatio.com.br/wp-admin", descricao: "" },
  { nome: "Sinch", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://messaging.wavy.global/", descricao: "" },
  { nome: "Sinch messaging", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://messaging.wavy.global/dashboard", descricao: "" },
  { nome: "Smartbrain API", categoria: "Outros", tipo: "Passbolt", url: "https://api.smartbraincloud.net:8099/api/v1/auth/login", descricao: "" },
  { nome: "Tapfiliate", categoria: "Marketing", tipo: "Passbolt", url: "https://tapfiliate.com", descricao: "" },
  { nome: "Tester Active Campaign", categoria: "Outros", tipo: "Passbolt", url: "https://www.activecampaign.com/br/", descricao: "" },
  { nome: "Treinamento Curso Certifiquei", categoria: "Produto", tipo: "Passbolt", url: "https://purchase.hotmart.com/purchase", descricao: "" },
  { nome: "Vapor.laravel.com", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://vapor.laravel.com/app", descricao: "" },
  { nome: "Wavy", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://messaging.wavy.global/dashboard", descricao: "" },
  { nome: "Windows server BI (RDP)", categoria: "Outros", tipo: "Passbolt", url: "195.154.28.146", descricao: "" },
  { nome: "Agora Pulse", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Ahrefs", categoria: "Marketing", tipo: "Passbolt", url: "https://ahrefs.com/user/login", descricao: "" },
  { nome: "Apple ID - Scanfii", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://appleid.apple.com/", descricao: "" },
  { nome: "Bannersnack", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Bannersnack Design", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Bannersnack Influencers", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Browserstack", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://www.browserstack.com/", descricao: "" },
  { nome: "Certifiquei", categoria: "Produto", tipo: "Passbolt", url: "https://certifiquei-cnpi.club.hotmart.com/", descricao: "" },
  { nome: "Certifiquei Compartilhado", categoria: "Produto", tipo: "Passbolt", url: "https://www.certifiquei.com.br/cursos/pdpe/", descricao: "" },
  { nome: "Cpf cnpj", categoria: "Outros", tipo: "Passbolt", url: "Cpfcnpj.com.br", descricao: "" },
  { nome: "Creative Tim", categoria: "Outros", tipo: "Passbolt", url: "https://www.creative-tim.com", descricao: "" },
  { nome: "Drive Drive", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "E-mail de Performance", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "E-mail suno@suno", categoria: "Produtividade", tipo: "Individual", url: "gmail.com", descricao: "" },
  { nome: "E-mail sunolivros", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Email/ YT LTStocks", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Email/ YT Nesta Casa", categoria: "Conteúdo", tipo: "Passbolt", url: "gmail.com", descricao: "" },
  { nome: "Email/ YT PQVNI", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Facebook Marcos Baroni", categoria: "Marketing", tipo: "Passbolt", url: "facebook.com", descricao: "" },
  { nome: "Facebook Tiago Reis pessoal", categoria: "Marketing", tipo: "Passbolt", url: "facebook.com", descricao: "" },
  { nome: "Fusioncharts support", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://support.fusioncharts.com/support/login", descricao: "" },
  { nome: "Giphy", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Gitlab SunoResarch", categoria: "Desenvolvimento", tipo: "Passbolt", url: "https://gitlab.com/", descricao: "" },
  { nome: "Gmail", categoria: "Produtividade", tipo: "Individual", url: "", descricao: "" },
  { nome: "Gmail - Scanfii", categoria: "Produtividade", tipo: "Individual", url: "https://accounts.google.com/", descricao: "" },
  { nome: "Hotmail/Skype", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Linkedin Suno Asset", categoria: "Marketing", tipo: "Passbolt", url: "https://www.linkedin.com", descricao: "" },
  { nome: "Linkpad Gian", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Baroni", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Linktree Noticias", categoria: "Marketing", tipo: "Passbolt", url: "https://linktr.ee/", descricao: "" },
  { nome: "Mindmeister", categoria: "Outros", tipo: "Passbolt", url: "https://www.mindmeister.com/", descricao: "" },
  { nome: "Mlabs Todos", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "NameCheap", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://www.namecheap.com/", descricao: "" },
  { nome: "Outline admin", categoria: "Produtividade", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Pingdom", categoria: "Infraestrutura", tipo: "Passbolt", url: "https://my.pingdom.com", descricao: "" },
  { nome: "Postman", categoria: "Desenvolvimento", tipo: "Passbolt", url: "postman.com", descricao: "" },
  { nome: "PPPI Mercado Livre", categoria: "Comercial", tipo: "Passbolt", url: "https://pppi.mercadolibre.com/", descricao: "" },
  { nome: "Reshape", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Shorby", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Social Rocket", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Streamyard", categoria: "Conteúdo", tipo: "Passbolt", url: "https://streamyard.com/login", descricao: "" },
  { nome: "Tubebuddy", categoria: "Outros", tipo: "Passbolt", url: "https://www.tubebuddy.com", descricao: "" },
  { nome: "Twitter Tiago Reis US", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "Twitter Wainberg", categoria: "Marketing", tipo: "Passbolt", url: "https://twitter.com/", descricao: "" },
  { nome: "VR Beneficios", categoria: "RH", tipo: "Passbolt", url: "https://www.vr.com.br/portal/portal-vr/login/", descricao: "" },
  { nome: "WebinarJam Midias Sociais", categoria: "Outros", tipo: "Passbolt", url: "", descricao: "" },
  { nome: "Wesley Hotmart", categoria: "Financeiro", tipo: "Passbolt", url: "https://app-vlc.hotmart.com/dashboard", descricao: "" },
  { nome: "Youtube Simpatio", categoria: "Conteúdo", tipo: "Passbolt", url: "", descricao: "" },
];
